name: Deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --production
      - name: Build site
        run: yarn build
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: {{.Project}}
          root: ./dist
          entrypoint: server/entry.mjs
